@TA_Apricode_HostAddress = https://localhost:7235


GET {{TA_Apricode_HostAddress}}/api/games?genre=string

###

GET {{TA_Apricode_HostAddress}}/api/games/all

###

POST {{TA_Apricode_HostAddress}}/api/games
Content-Type: application/json

{
    "title": "Example Game",
    "developer": "Example Developer",
    "genres": ["Action", "Adventure"]
}

###
